#!/usr/bin/env python

import os

APPNAME = 'DNS Client Tests'

top = '.'
out = 'build-tests'

# configuration options
def options(opt):
	opt.get_option_group('configure options')

# configures and builds individual tests in /cmocka-tests/test-fn
def configure(conf):
	print('prefix set to: ' + conf.options.prefix)
	print('src dir (blank: default): ' + conf.options.top)
	print('bld dir (blank: default): ' + conf.options.out)
	print('configuring test suites in build dir...')
	return

def build(bld):
	print('building cli_crypto_test...')
	bld.SAMBA_BINARY('cli_crypto_test',
			source='cli_crypto_test.c',
			deps='LIBTSOCKET tevent-util cmocka',
			install=False)

	print('building dns_tcp_test...')
	bld.SAMBA_BINARY('dns_tcp_test',
			source='dns_tcp_test.c',
			deps='LIBTSOCKET tevent-util cmocka',
			install=False)

	print('building dns_udp_test...')
	bld.SAMBA_BINARY('dns_udp_test',
			source='dns_udp_test.c',
			deps='LIBTSOCKET tevent-util cmocka',
			install=False)
	print('DONE')

# creates tarball
def dist(ctx):
	ctx.base_name = 'libcli-dns-tests'
	ctx.algo = 'tar.gz'
	ctx.excl = '**/wscript'
