#!/usr/bin/env python

import os

out = 'build-tests'

# configures and builds individual tests in /cmocka-tests/test-fn
def configure(conf):
	print('configuring test suites in ' + out + '...')
	return

def build(bld):
	print('building cli_crypto_test...')
	bld.SAMBA_BINARY('cli_crypto_test',
			source='cli_crypto_test.c',
			deps='LIBTSOCKET tevent-util cmocka',
			install=False)

	print('building dns_tcp_test...')
	bld.SAMBA_BINARY('dns_tcp_test',
			source='dns_tcp_test.c',
			deps='LIBTSOCKET tevent-util cmocka',
			install=False)

	print('building dns_udp_test...')
	bld.SAMBA_BINARY('dns_udp_test',
			source='dns_udp_test.c',
			deps='LIBTSOCKET tevent-util cmocka',
			install=False)
			
	print('DONE')
